import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
  title: 'Create App',
  description: 'Generated by create app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Header/>
          <main>
            {children}
          </main>
        <Footer/>
      </body>
    </html>
  )
}
